/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as RentalRouteImport } from './routes/rental'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ProdukRouteImport } from './routes/produk'
import { Route as PesananRouteImport } from './routes/pesanan'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as KabarRouteImport } from './routes/kabar'
import { Route as FlashSaleRouteImport } from './routes/flash-sale'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BantuanRouteImport } from './routes/bantuan'
import { Route as AkunRouteImport } from './routes/akun'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuksesOrderIdRouteImport } from './routes/sukses.$orderId'
import { Route as ProdukSlugRouteImport } from './routes/produk_.$slug'
import { Route as PembayaranOrderIdRouteImport } from './routes/pembayaran.$orderId'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalRoute = RentalRouteImport.update({
  id: '/rental',
  path: '/rental',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukRoute = ProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => rootRouteImport,
} as any)
const PesananRoute = PesananRouteImport.update({
  id: '/pesanan',
  path: '/pesanan',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const KabarRoute = KabarRouteImport.update({
  id: '/kabar',
  path: '/kabar',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashSaleRoute = FlashSaleRouteImport.update({
  id: '/flash-sale',
  path: '/flash-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BantuanRoute = BantuanRouteImport.update({
  id: '/bantuan',
  path: '/bantuan',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunRoute = AkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuksesOrderIdRoute = SuksesOrderIdRouteImport.update({
  id: '/sukses/$orderId',
  path: '/sukses/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk_/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PembayaranOrderIdRoute = PembayaranOrderIdRouteImport.update({
  id: '/pembayaran/$orderId',
  path: '/pembayaran/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/akun': typeof AkunRoute
  '/bantuan': typeof BantuanRoute
  '/checkout': typeof CheckoutRoute
  '/daftar': typeof DaftarRoute
  '/flash-sale': typeof FlashSaleRoute
  '/kabar': typeof KabarRoute
  '/keranjang': typeof KeranjangRoute
  '/masuk': typeof MasukRoute
  '/pesanan': typeof PesananRoute
  '/produk': typeof ProdukRoute
  '/profil': typeof ProfilRoute
  '/rental': typeof RentalRoute
  '/tentang': typeof TentangRoute
  '/pembayaran/$orderId': typeof PembayaranOrderIdRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/sukses/$orderId': typeof SuksesOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/akun': typeof AkunRoute
  '/bantuan': typeof BantuanRoute
  '/checkout': typeof CheckoutRoute
  '/daftar': typeof DaftarRoute
  '/flash-sale': typeof FlashSaleRoute
  '/kabar': typeof KabarRoute
  '/keranjang': typeof KeranjangRoute
  '/masuk': typeof MasukRoute
  '/pesanan': typeof PesananRoute
  '/produk': typeof ProdukRoute
  '/profil': typeof ProfilRoute
  '/rental': typeof RentalRoute
  '/tentang': typeof TentangRoute
  '/pembayaran/$orderId': typeof PembayaranOrderIdRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/sukses/$orderId': typeof SuksesOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/akun': typeof AkunRoute
  '/bantuan': typeof BantuanRoute
  '/checkout': typeof CheckoutRoute
  '/daftar': typeof DaftarRoute
  '/flash-sale': typeof FlashSaleRoute
  '/kabar': typeof KabarRoute
  '/keranjang': typeof KeranjangRoute
  '/masuk': typeof MasukRoute
  '/pesanan': typeof PesananRoute
  '/produk': typeof ProdukRoute
  '/profil': typeof ProfilRoute
  '/rental': typeof RentalRoute
  '/tentang': typeof TentangRoute
  '/pembayaran/$orderId': typeof PembayaranOrderIdRoute
  '/produk_/$slug': typeof ProdukSlugRoute
  '/sukses/$orderId': typeof SuksesOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/akun'
    | '/bantuan'
    | '/checkout'
    | '/daftar'
    | '/flash-sale'
    | '/kabar'
    | '/keranjang'
    | '/masuk'
    | '/pesanan'
    | '/produk'
    | '/profil'
    | '/rental'
    | '/tentang'
    | '/pembayaran/$orderId'
    | '/produk/$slug'
    | '/sukses/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/akun'
    | '/bantuan'
    | '/checkout'
    | '/daftar'
    | '/flash-sale'
    | '/kabar'
    | '/keranjang'
    | '/masuk'
    | '/pesanan'
    | '/produk'
    | '/profil'
    | '/rental'
    | '/tentang'
    | '/pembayaran/$orderId'
    | '/produk/$slug'
    | '/sukses/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/akun'
    | '/bantuan'
    | '/checkout'
    | '/daftar'
    | '/flash-sale'
    | '/kabar'
    | '/keranjang'
    | '/masuk'
    | '/pesanan'
    | '/produk'
    | '/profil'
    | '/rental'
    | '/tentang'
    | '/pembayaran/$orderId'
    | '/produk_/$slug'
    | '/sukses/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AkunRoute: typeof AkunRoute
  BantuanRoute: typeof BantuanRoute
  CheckoutRoute: typeof CheckoutRoute
  DaftarRoute: typeof DaftarRoute
  FlashSaleRoute: typeof FlashSaleRoute
  KabarRoute: typeof KabarRoute
  KeranjangRoute: typeof KeranjangRoute
  MasukRoute: typeof MasukRoute
  PesananRoute: typeof PesananRoute
  ProdukRoute: typeof ProdukRoute
  ProfilRoute: typeof ProfilRoute
  RentalRoute: typeof RentalRoute
  TentangRoute: typeof TentangRoute
  PembayaranOrderIdRoute: typeof PembayaranOrderIdRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
  SuksesOrderIdRoute: typeof SuksesOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental': {
      id: '/rental'
      path: '/rental'
      fullPath: '/rental'
      preLoaderRoute: typeof RentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk': {
      id: '/produk'
      path: '/produk'
      fullPath: '/produk'
      preLoaderRoute: typeof ProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesanan': {
      id: '/pesanan'
      path: '/pesanan'
      fullPath: '/pesanan'
      preLoaderRoute: typeof PesananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kabar': {
      id: '/kabar'
      path: '/kabar'
      fullPath: '/kabar'
      preLoaderRoute: typeof KabarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flash-sale': {
      id: '/flash-sale'
      path: '/flash-sale'
      fullPath: '/flash-sale'
      preLoaderRoute: typeof FlashSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bantuan': {
      id: '/bantuan'
      path: '/bantuan'
      fullPath: '/bantuan'
      preLoaderRoute: typeof BantuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun': {
      id: '/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AkunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sukses/$orderId': {
      id: '/sukses/$orderId'
      path: '/sukses/$orderId'
      fullPath: '/sukses/$orderId'
      preLoaderRoute: typeof SuksesOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk_/$slug': {
      id: '/produk_/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembayaran/$orderId': {
      id: '/pembayaran/$orderId'
      path: '/pembayaran/$orderId'
      fullPath: '/pembayaran/$orderId'
      preLoaderRoute: typeof PembayaranOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AkunRoute: AkunRoute,
  BantuanRoute: BantuanRoute,
  CheckoutRoute: CheckoutRoute,
  DaftarRoute: DaftarRoute,
  FlashSaleRoute: FlashSaleRoute,
  KabarRoute: KabarRoute,
  KeranjangRoute: KeranjangRoute,
  MasukRoute: MasukRoute,
  PesananRoute: PesananRoute,
  ProdukRoute: ProdukRoute,
  ProfilRoute: ProfilRoute,
  RentalRoute: RentalRoute,
  TentangRoute: TentangRoute,
  PembayaranOrderIdRoute: PembayaranOrderIdRoute,
  ProdukSlugRoute: ProdukSlugRoute,
  SuksesOrderIdRoute: SuksesOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
